Repository rl-institut/digipipe, pull requests merged in 2023-08, with the labels that each got.

#167 Fix/unstack ts warning
  CHANGELOG.md
  digipipe/esys/esys/tools/data_processing.py
Labels: bug :lady_beetle:

#160 Features/add biomass shares calc
  CHANGELOG.md
  digipipe/store/appdata/datapackage/config.yml
  digipipe/store/datasets/demand_heat_region/config.yml
  digipipe/store/datasets/demand_heat_region/create.smk
  digipipe/store/datasets/demand_heat_region/dataset.md
  digipipe/store/preprocessed/bmwk_long_term_scenarios/config.yml
  digipipe/store/preprocessed/dbfz_biomass_capacity_rel/config.yml
  digipipe/store/preprocessed/dbfz_biomass_capacity_rel/create.smk
  digipipe/store/preprocessed/dbfz_biomass_capacity_rel/data/.gitkeep
  digipipe/store/preprocessed/dbfz_biomass_capacity_rel/dataset.md
  digipipe/store/preprocessed/module.smk
  digipipe/store/raw/bmwk_long_term_scenarios/dataset.md
  digipipe/store/raw/dbfz_biomass_heat_capacities/data/.gitkeep
  digipipe/store/raw/dbfz_biomass_heat_capacities/dataset.md
  digipipe/store/raw/dbfz_biomass_heat_capacities/metadata.json
  docs/datasets/datasets_datasets.md
  docs/datasets/preprocessed_datasets.md
  docs/datasets/raw_datasets.md
Labels: dataset :scroll:

#143 Fix/clean rule
  CHANGELOG.md
  digipipe/workflow/Snakefile
  digipipe/workflow/WORKFLOW.md
Labels: bug :lady_beetle:

#176 Features/#171 add osm to install instructions
  CHANGELOG.md
  digipipe/workflow/WORKFLOW.md
  docs/sections/installation.md
Labels: documentation :memo:

#180 Features/#178 remove redundant sliders from datapackage
  CHANGELOG.md
  digipipe/store/datasets/app_settings/config.yml
  digipipe/store/datasets/app_settings/scripts/panels.py
Labels: 4digiplan :rocket:

#188 Features/#181 #184 update sliders app settings
  CHANGELOG.md
  digipipe/store/datasets/app_settings/config.yml
  digipipe/store/datasets/app_settings/create.smk
  digipipe/store/datasets/app_settings/scripts/panels.py
  docs/sections/installation.md
Labels: 4digiplan :rocket:
